name: test action1
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  htmlUpdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

#test
#update s3 bucket when new html is pushed

# - name: Checkout repo
#   uses: actions/checkout@v2.5.0

# - name: Configure AWS Credentials
#   uses: aws-actions/configure-aws-credentials@v1
#   with:
#     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#     aws-region: us-east-2