on:
  pull_request:
    paths:
      - 'resume/index.html'


jobs:
  htmlUpdate:
    runs-on: ubuntu-latest
    env: 
      S3_RESUME: ${{ secrets.S3_RESUME }}
    steps:

      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload html file
        run: |
          aws s3 cp ./resume/index.html s3://$S3_RESUME/

      - name: Upload CSS
        run: |
          aws s3 cp ./resume/style.css s3://$S3_RESUME/

      - name: Upload CSS
        run: |
          aws s3 cp ./resume/app.js s3://$S3_RESUME/