# This should test the javascript that is being updated.

# on:
#   workflow_call:
#     secrets:
#       AWS_ACCESS_KEY_ID:
#         required: true
#       AWS_SECRET_ACCESS_KEY:
#         required: true
#       S3_RESUME:
#         required: true

on:
  push:
    paths:
      - 'resume/app.js'

jobs:
  jsUpdate:
    runs-on: ubuntu-latest
    env: 
      S3_RESUME: ${{ secrets.S3_RESUME }}
    steps:

      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload .js file
        run: |
          aws s3 cp ./resume/app.js s3://$S3_RESUME/