# this should test lambda python and update the lambda with the new .zip or upload into new s3 bucket and then update the function

on:
  push:
    paths:
      - 'counter/*'

jobs:
  jsUpdate:
    runs-on: ubuntu-latest
    env: 
      S3_RESUME: ${{ secrets.S3_RESUME }}
    steps:

      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2