name: main call

on:
  workflow_dispatch:

  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # release:
  #   types:
  #     - published

jobs:

  master:
    # if: ${{ github.ref == 'refs/heads/master' }}
    uses: ./.github/workflows/workflows.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      S3_RESUME: ${{ secrets.S3_RESUME}}
